version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app/stutter-enhancer
      - /app/node-modules
    environment:
      - CHOKIDAR_USEPOLLING=true