apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - port: 8001         # Choose a port if it listens to one, or omit if it's a worker
      targetPort: 8001
  type: ClusterIP
