version: '3.9'

networks:
  ainet:
    driver: bridge

volumes:
  minio-vol:
  redis-vol:
  db-vol:



services:
  web:
    image: web
    build:
      context: .
      dockerfile: web.dockerfile
    container_name: web
    env_file:
      - .env
    ports:
     - "8000:8000"
    command: /bin/sh -c "sleep 30 && (python deployment/setup_minio.py & /bin/sh /src/app/tasks/localworker.sh & python deployment/setup_db.py & uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload)"
    restart: on-failure
    depends_on:
      - minio
      - redis
      - postgres
    networks:
      - ainet
    volumes:
      - ../:/src/ #share codebase


  postgres:
    image: bitnami/postgresql:14.17.0
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    restart: on-failure
    networks:
      - ainet
    volumes:
      - db-vol:/dbstorage



  ai-service:
    image: stts
    build:
      context: .
      dockerfile: ai.dockerfile
    container_name: stts
    env_file:
      - .env
    command: /bin/sh -c "/bin/sh /src/app/tasks/aiworker.sh"
    restart: on-failure
    depends_on:
      - redis
    networks:
      - ainet
    volumes:
      - ../:/src/ #share codebase
      


  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - ainet
    volumes:
      - redis-vol:/volstorage



  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /volstorage --console-address :9001
    restart: on-failure
    networks:
      - ainet
    volumes:
      - minio-vol:/volstorage




  # frontend:
  #   image: yourimage
  #   container_name: client
  #   restart: on-failure
  #   ports:
  #     - x:x 

  #   #...add otherconfigs

  #   network:
  #     - ainet
  #   volume:
  #     - yourvolumeifyouneedone


# docker run -d -it -p 9000:9000 -e MINIO_ROOT_USER=youraccesskey -e MINIO_ROOT_PASSWORD=yoursecretkey --name minio -v miniovol:/ostorage minio/minio:RELEASE.2025-04-08T15-41-24Z server /ostorage